export const countryList = [
  "Australia",
  "Austria",
  "Belgium",
  "Brazil",
  "Bulgaria",
  "Canada",
  "China",
  "Germany",
  "Estonia",
  "Hungary",
  "Iceland",
  "Italy",
  "Luxembourg",
  "Malta",
  "Netherlands",
  "New Zealand",
  "Norway",
  "Portugal",
  "Romania",
  "Russian Federation",
  "Slovakia",
  "Slovenia",
  "Sweden",
  "Switzerland",
  "Turkey",
  "Ukraine",
  "United Emirates",
  "United Kingdom",
  "United States",
  "Uruguay",
];
